name: Feature
description: A request, idea, or new functionality

body:
  - type: textarea
    id: feat_desc
    attributes:
      label: Feature description
      description: Describe the desired functionality using As a / I want / So that
      placeholder: |
        As a...
        I want...
        So that...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: List specific conditions that must be met for completion.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
