name: Story
description: A user requirement describing valuable functionality

body:
  - type: markdown
    attributes:
      value: "## Story description"

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Use the format As a / I want / So that
      placeholder: |
        As a...
        I want...
        So that...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        
        ---
        ## Acceptance criteria

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
