name: Story
description: A user requirement describing valuable functionality

body:
  - type: markdown
    attributes:
      value: "## Story description"

  - type: textarea
    id: user_story
    attributes:
      description: Describe the desired functionality using As a / I want / So that
      placeholder: |
        As a...
        I want...
        So that...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        
        ---
        ## Acceptance criteria

  - type: textarea
    id: acceptance_criteria
    attributes:
      description: List specific conditions that must be met for completion.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
